import { drizzle } from "drizzle-orm/better-sqlite3";
import { migrate } from "drizzle-orm/better-sqlite3/migrator";
import Database from "better-sqlite3";
import * as schema from '@/db/schema';

export function createTestDb() {
  // Create an in-memory SQLite database
  const sqlite = new Database(":memory:");
  const db = drizzle(sqlite, { schema });

  // Run migrations generated by drizzle-kit
  migrate(db, { migrationsFolder: "./migrations" });

  return { db, sqlite };
}